### ISSUE TITLE
Dropbox SFZ version

### ISSUE THREAD

**Issue by IsaakCode** [endolith/Salamander-Drumkit#1]
The Dropbox link to the SFZ version returns an 404 error. The content is no longer available. Please re-upload!

**Comment by endolith** [comment]
You mean https://www.dropbox.com/s/i24fgjryj05w5gp/Salamander_Drumkit_sforzando.rar?dl=0?

It's in the repo: https://github.com/endolith/Salamander-Drumkit/blob/master/Salamander%20Drumkit.sfz

**Comment by IsaakCode** [comment]
Sorry for the vague comment! The SFZ that's missing (the dysfunctional Dropbox link) was the specific SFZ mapping for Sforzando. That one seems to have disappeared. Could it be uploaded to the Github repo aswell?

**Comment by endolith** [comment]
What is the link?

**Comment by IsaakCode** [comment]
The one that is mentioned in the readme. It appears to be the same as the one you posted above:
https://www.dropbox.com/s/i24fgjryj05w5gp/Salamander_Drumkit_sforzando.rar?dl=0

So they are the exact same mappings as in the repo I guess. Maybe remove the Dropbox link, because it's a) dysfunctional and b) confusing. 

I got the impression there were two mappings: 1. generic SFZ mapping, 2. special SFZ mapping for Sforzando that maybe uses additional functions only present in Sforzando. 

Thanks for the quick reply and sorry for bothering you in vein.

**Comment by endolith** [comment]
I don't have the rar file anymore, but [my commit message](https://github.com/endolith/Salamander-Drumkit/commit/60756b9b23ce0e13908919b8f6e45f21f0b57cf2) was "Add kinwie's rewritten version for sforzando" and that link is from kinwie's readme file, so I think it's the same thing.

**Comment by endolith** [comment]
The original source is https://www.kvraudio.com/forum/viewtopic.php?p=6189825#p6189825
